/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'falvojr' at '6/22/17 3:00 PM' with Gradle 2.14.1
 *
 * @author falvojr, @date 6/22/17 3:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
